site_name: Azure DevOps To AWS S3 Repository Archiver
site_description: 'Documentation for the Azure DevOps To AWS S3 Repository Archiver'
site_author: 'Stefan Freitag'
docs_dir: docs/
repo_name: 'stefanfreitag/azure_s3_repository_archiver'
repo_url: 'https://github.com/stefanfreitag/azure_s3_repository_archiver'
edit_uri: blob/main/docs/
nav:
    - Home: index.md
theme:
  name: 'material'
  palette:
    scheme: default

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences